version: '3.9'
services:
  db:
    container_name: faceup_db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_SQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_SQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d

  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=testkey
      - AWS_SECRET_ACCESS_KEY=testsecret